export const CATEGORIES = [
  "Electronics",
  "Clothing",
  "Food & Beverages",
  "Home & Garden",
  "Sports & Outdoors",
  "Books",
  "Toys & Games",
  "Beauty & Health",
  "Automotive",
  "Office Supplies",
  "Pet Supplies",
  "Music & Instruments",
  "Garden & Outdoor",
  "Furniture",
  "Jewelry & Accessories",
];

export const SHOPS: { id: string; name: string }[] = [
  { id: "shop_001", name: "TechZone Store" },
  { id: "shop_002", name: "FashionHub" },
  { id: "shop_003", name: "GreenMart" },
  { id: "shop_004", name: "HomeDepot Online" },
  { id: "shop_005", name: "SportsPro" },
  { id: "shop_006", name: "BookWorld" },
  { id: "shop_007", name: "ToysRUs" },
  { id: "shop_008", name: "BeautyBox" },
  { id: "shop_009", name: "AutoParts Plus" },
  { id: "shop_010", name: "OfficeWorld" },
  { id: "shop_011", name: "PetParadise" },
  { id: "shop_012", name: "MelodyShop" },
  { id: "shop_013", name: "GardenGlory" },
  { id: "shop_014", name: "LuxuryFurnish" },
  { id: "shop_015", name: "GemCraft Jewelry" },
  { id: "shop_016", name: "CoolGadgets" },
  { id: "shop_017", name: "OutdoorAdventure" },
  { id: "shop_018", name: "HealthPlus" },
  { id: "shop_019", name: "KitchenKing" },
  { id: "shop_020", name: "GameZone" },
];

export const RANDOM_IMAGES = [
  "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500",
  "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
  "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
  "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500",
  "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=500",
  "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=500",
  "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
  "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=500",
  "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500",
  "https://images.unsplash.com/photo-1585155770447-2f66e2a397b5?w=500",
  "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500",
  "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=500",
  "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500",
  "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500",
  "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500",
  "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=500",
  "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=500",
  "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=500",
  "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=500",
  "https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=500",
  "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500",
];

export const ADJECTIVES = [
  "Pro",
  "Elite",
  "Ultra",
  "Premium",
  "Deluxe",
  "Plus",
  "Max",
  "Lite",
  "Advanced",
  "Smart",
  "Mini",
  "Compact",
  "Heavy-Duty",
  "Slim",
  "Turbo",
  "Eco",
  "Classic",
  "Next-Gen",
  "Signature",
  "Limited Edition",
];

export const PRODUCT_NOUNS: Record<string, string[]> = {
  Electronics: [
    "Bluetooth Headphones",
    "Wireless Earbuds",
    "Smart Watch",
    "Fitness Tracker",
    "Portable Speaker",
    "Laptop Stand",
    "Mechanical Keyboard",
    "Gaming Mouse",
    "USB-C Hub",
    "Webcam HD",
    "Smart Thermostat",
    "Noise-Cancelling Headset",
    "LED Desk Lamp",
    "Portable SSD",
    "Phone Gimbal",
    "Action Camera",
  ],
  Clothing: [
    "Running Jacket",
    "Merino Wool Sweater",
    "Slim-Fit Chinos",
    "Graphic Tee",
    "Waterproof Parka",
    "Linen Shirt",
    "Fleece Hoodie",
    "Cargo Shorts",
    "Compression Leggings",
    "Denim Jacket",
    "Polo Shirt",
    "Bomber Jacket",
  ],
  "Food & Beverages": [
    "Cold Brew Coffee Kit",
    "Matcha Powder",
    "Protein Powder",
    "Energy Bars Pack",
    "Artisan Olive Oil",
    "Organic Honey",
    "Dark Chocolate Box",
    "Green Tea Set",
    "Hot Sauce Collection",
    "Granola Mix",
    "Spice Rack Set",
    "Nut Butter Bundle",
  ],
  "Home & Garden": [
    "Air Purifier",
    "Coffee Maker",
    "Robot Vacuum",
    "Instant Pot",
    "Smart Plug",
    "Diffuser",
    "Wall Art Print",
    "Planter Set",
    "Candle Bundle",
    "Storage Ottoman",
    "Throw Pillow Set",
    "LED Strip Lights",
  ],
  "Sports & Outdoors": [
    "Yoga Mat",
    "Resistance Bands Set",
    "Jump Rope",
    "Water Bottle",
    "Running Shoes",
    "Hiking Backpack",
    "Camping Tent",
    "Trekking Poles",
    "Foam Roller",
    "Gym Gloves",
    "Dumbbell Set",
    "Swim Goggles",
  ],
  Books: [
    "Self-Help Guide",
    "Sci-Fi Novel",
    "Cookbook Collection",
    "Business Strategy Book",
    "History Atlas",
    "Poetry Collection",
    "Programming Handbook",
    "Art Journal",
    "Travel Memoir",
    "Mystery Thriller",
    "Children's Picture Book",
    "Finance Guide",
  ],
  "Toys & Games": [
    "Building Blocks Set",
    "Board Game",
    "Remote Control Car",
    "Puzzle 1000-Piece",
    "STEM Robot Kit",
    "Card Game",
    "Stuffed Animal",
    "Drone Starter Kit",
    "Strategy Board Game",
    "Educational Flashcards",
    "Play-Doh Set",
    "Marble Run",
  ],
  "Beauty & Health": [
    "Vitamin C Serum",
    "Jade Roller",
    "Beard Grooming Kit",
    "Hair Mask Pack",
    "Essential Oil Set",
    "Face Mask Bundle",
    "Electric Toothbrush",
    "Lip Care Set",
    "Multivitamin Pack",
    "Collagen Supplement",
    "Acne Patch Pack",
    "Sunscreen SPF50",
  ],
  Automotive: [
    "Dash Cam",
    "Car Phone Mount",
    "Tire Inflator",
    "Car Vacuum Cleaner",
    "LED Headlight Kit",
    "Seat Covers Set",
    "GPS Navigator",
    "Car Jump Starter",
    "Steering Wheel Cover",
    "Air Freshener Pack",
    "OBD2 Scanner",
    "Windshield Wiper Blades",
  ],
  "Office Supplies": [
    "Ergonomic Chair",
    "Standing Desk Converter",
    "Planner Notebook",
    "Pen Set",
    "Desk Organizer",
    "Monitor Riser",
    "Whiteboard",
    "Cable Management Kit",
    "Document Shredder",
    "Stapler Set",
    "Tape Dispenser",
    "File Cabinet",
  ],
  "Pet Supplies": [
    "Interactive Cat Toy",
    "Dog Harness",
    "Pet Grooming Kit",
    "Orthopedic Dog Bed",
    "Smart Pet Feeder",
    "Aquarium Starter Kit",
    "Bird Cage Deluxe",
    "Cat Tree Tower",
    "Pet GPS Tracker",
    "Dog Training Clicker",
    "Flea Treatment Pack",
    "Pet Water Fountain",
  ],
  "Music & Instruments": [
    "Acoustic Guitar",
    "Digital Piano",
    "MIDI Controller",
    "Drum Practice Pad",
    "Ukulele Starter Kit",
    "Metronome Digital",
    "Capo & Picks Set",
    "Violin",
    "Music Stand Folding",
    "Saxophone",
    "Audio Interface",
    "Studio Headphones",
  ],
  "Garden & Outdoor": [
    "Garden Hose Reel",
    "Pruning Shears",
    "Raised Garden Bed",
    "Compost Bin",
    "Solar Garden Lights",
    "Lawn Aerator Shoes",
    "Bird Feeder",
    "Patio Umbrella",
    "Drip Irrigation Kit",
    "Garden Kneeler",
    "Seed Starter Kit",
    "Outdoor Thermometer",
  ],
  Furniture: [
    "Bookshelf 5-Tier",
    "L-Shaped Desk",
    "Accent Chair",
    "TV Stand",
    "Bar Cart",
    "Floating Shelves",
    "Nightstand with Drawer",
    "Foldable Dining Table",
    "Ottoman Bench",
    "Room Divider Screen",
    "Storage Cube",
    "Recliner Chair",
  ],
  "Jewelry & Accessories": [
    "Sterling Silver Bracelet",
    "Gold-Plated Necklace",
    "Stud Earring Set",
    "Leather Wallet",
    "Polarized Sunglasses",
    "Minimalist Ring",
    "Canvas Tote Bag",
    "Silk Scarf",
    "Leather Belt",
    "Beaded Anklet",
    "Travel Jewelry Case",
    "Watch Band Set",
  ],
};

export const PRICE_RANGES: Record<string, [number, number]> = {
  Electronics: [29.99, 899.99],
  Clothing: [14.99, 299.99],
  "Food & Beverages": [4.99, 89.99],
  "Home & Garden": [19.99, 499.99],
  "Sports & Outdoors": [9.99, 349.99],
  Books: [5.99, 49.99],
  "Toys & Games": [9.99, 199.99],
  "Beauty & Health": [7.99, 149.99],
  Automotive: [14.99, 399.99],
  "Office Supplies": [12.99, 699.99],
  "Pet Supplies": [9.99, 249.99],
  "Music & Instruments": [49.99, 1499.99],
  "Garden & Outdoor": [12.99, 299.99],
  Furniture: [79.99, 1999.99],
  "Jewelry & Accessories": [9.99, 499.99],
};

export const DESCRIPTION_TEMPLATES: ((name: string, cat: string) => string)[] =
  [
    (name, cat) =>
      `The ${name} is engineered for ${cat.toLowerCase()} enthusiasts who demand the best. Crafted with premium materials and precision engineering, it delivers outstanding performance and reliability in every use.`,
    (name, cat) =>
      `Introducing the ${name} — a game-changer in the ${cat.toLowerCase()} space. Featuring cutting-edge design and smart functionality, it's built for people who refuse to settle for ordinary.`,
    (name) =>
      `The ${name} combines form and function seamlessly. Whether you're at home, the gym, or on the go, this product adapts to your lifestyle with intuitive ease and durable construction.`,
    (name, cat) =>
      `Elevate your ${cat.toLowerCase()} experience with the ${name}. Backed by industry-leading quality standards, it features an ergonomic design and long-lasting materials that stand the test of time.`,
    (name) =>
      `The ${name} is your go-to choice for quality and value. Rigorously tested and loved by thousands of customers, it offers a seamless blend of style, performance, and affordability.`,
    (name, cat) =>
      `Looking for the ultimate ${cat.toLowerCase()} upgrade? The ${name} delivers exactly that. With an eco-conscious build and innovative features, it's designed for the modern, mindful consumer.`,
    (name) =>
      `The ${name} sets a new benchmark in its category. Its precision-engineered components and intuitive interface make it a must-have for both beginners and seasoned users alike.`,
  ];

export function randomElement<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export function randomPrice(category: string): number {
  const [min, max] = PRICE_RANGES[category] ?? [9.99, 499.99];
  return parseFloat((Math.random() * (max - min) + min).toFixed(2));
}

export function generateProductName(category: string): string {
  const nouns = PRODUCT_NOUNS[category] ?? PRODUCT_NOUNS.Electronics;
  const noun = randomElement(nouns);
  return Math.random() > 0.4 ? `${randomElement(ADJECTIVES)} ${noun}` : noun;
}
